services:
  - type: web
    name: uc-quantum-prediction
    env: docker
    plan: free
    region: oregon
    buildCommand: docker build -t uc-quantum-prediction .
    startCommand: ./start.sh
    envVars:
      - key: PORT
        value: 10000
      - key: MONGO_URL
        sync: false
      - key: MALLOC_ARENA_MAX
        value: 2
      - key: PYTHONUNBUFFERED
        value: 1
    healthCheckPath: /health
    autoDeploy: true
